---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: atlantis
  namespace: atlantis
  labels:
    app: atlantis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlantis
  template:
    metadata:
      labels:
        app: atlantis
    spec:
      containers:
        - name: atlantis
          image: ghcr.io/runatlantis/atlantis
          # command:
          #   - /bin/sh
          #   - -c
          #   - "sleep infinity"
          envFrom:
            - secretRef:
                name: atlantis-auth
            - configMapRef:
                name: atlantis-env
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4141
          ports:
            - containerPort: 4141
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: atlantis
spec:
  selector:
    app: atlantis
  ports:
    - protocol: TCP
      port: 4141
      targetPort: 4141