# fly.toml file generated for spring-breeze-567 on 2023-02-09T19:26:41-05:00

app = "spring-breeze-567"

[env]
  ATLANTIS_LOG_LEVEL = "info"

[[services]]
  internal_port = 4141
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
